name: 'Auto Semantic Version'
description: 'Generate a version based on commits and tags information of your repository'
inputs:
  release:
    description: 'Label for the release versions'
    required: false
  namespace:
    description: 'Label to specify a namespace'
    required: false
outputs:
  version:
    description: 'The Version Generated'
runs:
  using: 'node12'
  main: 'dist/main.js'
